[package]
name = "deyk-client"
version = "0.1.0"
edition = "2024"

[dependencies]
p256 = { version = "0.13", features = ["ecdh", "ecdsa", "pkcs8"] }
aes-siv = "0.7.0"
hkdf = "0.12"
sha2 = "0.10"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
yubikey = { version = "0.8", features = ["untested"] }
anyhow = "1.0"
rand = "0.8"
zeroize = { version = "1.8.2", features = ["derive"] }
ct-codecs = "1.1.6"
