[package]
name = "deyk-server"
version = "0.1.0"
edition = "2024"

[dependencies]
p256 = { version = "0.13", features = ["ecdh", "pkcs8"] }
aes-siv = "0.7.0"
hkdf = "0.12"
sha2 = "0.10"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
dialoguer = "0.11"
rand = "0.8"
anyhow = "1.0"
